board:
  dir: up          #アップロードするディレクトリ
  maxsize: 2048    #アップロード最大サイズ(KB)
  ext: jpg,png,gif #許可する拡張子、カンマ区切り
	maxfiles: 5000   #最大ファイル数
  prefix: null     #ファイルのプレフィックス
arrow: #http://php.net/manual/ja/function.exif-imagetype.php
  gif: IMAGETYPE_GIF    #gif
  jpg: IMAGETYPE_JPEG   #jpg
  png: IMAGETYPE_PNG    #png
  bmp: IMAGETYPE_BMP    #bmp
admin:
  id: admin        #変更すること
  pass: qwer       #変更すること
  email: ahumau_nejitu@icloud.com #管理者メール
